<string name="facebook_pref">FBAdPrefs</string>
    <string name="device_id_hash">deviceIdHash</string>
    <string name="custom_device_hash">nkp</string>
    <string name="name">BIG FONT</string>
    <string name="deny">доступ к камере запрещен</string>
    <string name="custom_history">Пользовательская история</string>
    <string name="history_list_is_empty">Нет истории, чтобы показать</string>
    <string name="updateVip">Обновить VIP-версию</string>
    <string name="contentBodyIap1">Используйте новейшие функции в будущем</string>
    <string name="contentBodyIap2">Удалить рекламу</string>
    <string name="govipLife">Go VIP пожизненная версия</string>
    <string name="useVip3Days">Используйте VIP-версию 3 дня</string>
    <string name="no">Нет</string>
    <string name="click_to_custom_font">Нажмите здесь, чтобы изменить размер шрифта</string>
    <string name="click_to_enter_setting">Нажмите здесь, чтобы войти в настройки</string>
    <string name="click_to_see_history">Нажмите здесь, чтобы увидеть историю</string>
    <string name="success">Успех</string>
    <string name="font_size_changed">РАЗМЕР ШРИФТА ИЗМЕНЕН!</string>
    <string name="dialog_choose_answer">Вы уверены, что сделаете это изменение?</string>
    <string name="history">История</string>
    <string name="cutom_font_size">Пользовательский размер шрифта</string>
    <string name="install">Установить</string>
    <string name="more_app">Больше приложений</string>
    <string name="browser_not_found">Браузер не найден</string>
    <string name="i_understand">Я понимаю</string>
    <string name="loading">Загрузка...</string>
    <string name="open">Открытым</string>
    <string name="descriptionSonsor">Объявления Экомобайл</string>
    <string name="start">Начинать</string>
    <string name="skip_ad">Пропустить рекламу</string>
    <string name="no_browser_to_open">Браузер не найден</string>
    <string name="fanpage_facebook">Фан-страница Facebook</string>
    <string name="download_4k_wallpaper_now">Скачать 4K обои СЕЙЧАС</string>
    <string name="revert">Отменить</string>
    <string name="text_custom">Это демонстрационный текст.</string>
    <string name="text_custom_2">Big Font — отличное приложение для настройки размера шрифта. Мы надеемся, что с нашей помощью вы сможете улучшить эксперименты при использовании телефона.</string>
    <string name="text_custom_3">С наилучшими пожеланиями</string>
    <string name="text_custom_4">Команда разработчиков большого шрифта.</string>
    <string name="enlarge_font_size">УВЕЛИЧИТЬ РАЗМЕР ШРИФТА</string>
    <string name="feed_back">Обратная связь</string>
    <string name="feed_back_2">Обратная связь</string>
    <string name="crash">Крушение</string>
    <string name="not_working">Не работает</string>
    <string name="not_enlarge">Не увеличивать</string>
    <string name="send">послать</string>
    <string name="tag">ТЕГ</string>
    <string name="report">ОТЧЕТ</string>
    <string name="media_attachment">МЕДИА ПРИЛОЖЕНИЕ</string>
    <string name="you_can_attach_a_screenshot_or_video_describing_the_error_you_encountered">Вы можете прикрепить скриншот или видео с описанием возникшей ошибки..</string>
    <string name="do_you_have_any_suggestion_for_us_if_you_have_any_idea_for_improve_or_complain_about_our_service_don_t_hesitate_to_send_us_a_mail_thank_you">У вас есть какие-либо предложения для нас? Если у вас есть идеи по улучшению или вы жалуетесь на наш сервис, не стесняйтесь, присылайте нам письмо. Спасибо.</string>
    <string name="give_us_some_advice">Дайте нам несколько советов, чтобы улучшить наше приложение</string>
    <string name="tv_permission_denied">Чтобы использовать эту функцию, вам необходимо предоставить разрешение</string>
    <string name="content_notification"> Защитите свое приложение. </string>
    <string name="go_to_setting">Перейти к настройке</string>
    <string name="share_app">Поделиться приложением</string>
    <string name="retry_now">Повторить попытку</string>
    <string name="error_request">Не удалось подключиться к серверу. Пожалуйста, проверьте свой интернет</string>
    <string name="customize">Настроить</string>
